name: Docker Image CI

on:
  push:
    tags:
      - 'v*' 

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        TAG=$(echo $GITHUB_REF | cut -d / -f 3)
        echo "tag: $TAG"
        ls
        pwd
        docker build -t my-image-name:${TAG} .
 
