name: Docker Image CI

on:
  push:
    tags:
      - 'v*' 

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Build the Docker image
      run: |
        TAG=$(echo $GITHUB_REF | cut -d / -f 3)
        docker build . --file ./Dockerfile --tag my-image-name:$TAG
 
