name: Docker CI

on:
  push:
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+'

jobs:
  mvn-test:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout to source code
      uses: actions/checkout@v2
      
    - name: Set up JDK 11 for the tests
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        
    - name: Start Redis for the integration tests
      uses: supercharge/redis-github-action@1.1.0
      with:
        redis-version: 6
        
    - name: Maven test
      run: mvn -B test

  docker-build-push:
    runs-on: ubuntu-latest
    needs: mvn-test
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
    
    - name: Build and push the Docker image
      run: |
        # examples of tag: v1, v1.4, v1.4.5
        TAG=$(echo $GITHUB_REF | cut -d / -f 3)
        INPUT_VERSION=$(echo $TAG | cut -d 'v' -f 2)

        SPLITTED=(${INPUT_VERSION//./ })
        for i in {0..2}
        do
           [ "${SPLITTED[$i]}" != "" ] || SPLITTED[$i]=0
        done
        
        MAJOR_TAG=${SPLITTED[0]}
        MINOR_TAG=$MAJOR_TAG.${SPLITTED[1]}
        PATCH_TAG=$MINOR_TAG.${SPLITTED[2]}

        IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/tomcat-redis-manager

        # examples of docker tag generation:
        # | git tag | generated docker tags |
        # |---------|-----------------------|
        # | v1      | 1, 1.0, 1.0.0, latest |
        # | v1.2    | 1, 1.2, 1.2.0, latest |
        # | v1.2.3  | 1, 1.2, 1.2.3, latest |
        
        docker build . --file ./Dockerfile --tag $IMAGE_NAME:$MAJOR_TAG --tag $IMAGE_NAME:$MINOR_TAG --tag $IMAGE_NAME:$PATCH_TAG --tag $IMAGE_NAME:latest

        # push all generated tags
        docker push -a $IMAGE_NAME

  build:
    name: Create Release
    needs: docker-build-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: echo ${{ github.ref }} | cut -d v -f 2
          body: |
            Changes in this Release
             - First Change
             - Second Change
          draft: false
          prerelease: false

